---
- name: SETUP TOWER FOR CLOSED LOOP INCIDENT MGMT DEMO
  hosts: aap2.example.com
  connection: local
  become: true
  gather_facts: false
  vars:
    aap_username: "admin"
    aap_password: ""

  tasks:
    - name: import login credentials for servicenow
      include_vars: "{{lookup('first_found', login_info)}}"
      vars:
        login_info:
          - 'private.yml'
          - 'login_info.yml'

    - name: move playbooks to /var/lib/awx/projects/snow_demo
      copy:
        src: "{{playbook_dir}}/"
        dest: /var/lib/awx/projects/snow_demo/
      become: true
      become_method: sudo
      become_user: awx
      run_once: true
      delegate_to: localhost

    - name: add project to aap
      tower_project:
        name: SNOW_CL
        local_path: snow_demo
        organization: Default
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_host: https://aap2.example.com
        aap_verify_ssl: false
      run_once: true
      delegate_to: localhost

    - name: add servicenow custom cred
      aap_credential_type:
        name: "SNOW_CL Credential"
        description: Credential type for SNOW
        inputs: "{{ lookup('file', playbook_dir + '/custom_cred/inputs.yml') | from_yaml }}"
        injectors: "{{ lookup('file', playbook_dir + '/custom_cred/injector.yml') | from_yaml }}"
        state: present
        kind: cloud
        aap_username: "{{ aap_username }}"
        aap_password: "{{ aap_password }}"
        aap_host: https://aap2.example.com
        validate_certs: false

    - name: Add Custom Credential
      aap_credential:
